Metaprogramacao adicionada! :) no ./configure no cuda e' possivel indicar o numero de blocos e threads

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,10 +1,60 @@
 #!/bin/bash
 
+#die () {
+#    echo >&2 "$@"
+#    exit 1
+#}
+
+EX_UNKNOWN=1
+
+warning()
+{
+    # Output warning messages
+    # Color the output red if it's an interactive terminal
+    # @param $1...: Messages
+
+    test -t 1 && tput setf 4
+
+    printf '%s\n' "$@" >&2
+
+    test -t 1 && tput sgr0 # Reset terminal
+    true
+}
+
+error()
+{
+    # Output error messages with optional exit code
+    # @param $1...: Messages
+    # @param $N: Exit code (optional)
+
+    messages=( "$@" )
+
+    # If the last parameter is a number, it's not part of the messages
+    last_parameter="${messages[@]: -1}"
+    if [[ "$last_parameter" =~ ^[0-9]*$ ]]
+    then
+        exit_code=$last_parameter
+        unset messages[$((${#messages[@]} - 1))]
+    fi
+
+    warning "${messages[@]}"
+
+    exit ${exit_code:-$EX_UNKNOWN}
+}
+
+[ "$#" -ne 1 ] || error "2 argument required"
+echo $1 | grep -E -q '^[0-9]+$' || error "Numeric argument required, $1 provided"
+echo $2 | grep -E -q '^[0-9]+$' || error  "Numeric argument required, $2 provided"
+
+
+src="documentation/"
 DOC_IMAGE="cuda.jpg"
+CODVECTOR_PATH="_Codificador"
+
 
 echo -e "\nConfiguring ...";
 
-src="documentation/"
+
     
 for dir in `ls "$src/"`
 do
@@ -20,6 +70,21 @@ tree -o documentation/tree.out #>/dev/null 2>&1
 echo -e "Generating documentation ...";
 cd _Codificador/
 make docs >/dev/null 2>&1
+
+
+
+# meta programming
+
+new_line_block="const int G_BlocksPerGrid = "$1";"
+new_line_threads="const int G_ThreadsPerBlock = "$2";"
+
+perl -pe "s/.*/$new_line_block/ if $. == 102" < main.cu > main.cu_temp #>/dev/null 2>&1
+mv main.cu_temp main.cu
+echo -e "Blocks defined: $1";
+
+perl -pe "s/.*/$new_line_threads/ if $. == 103" < main.cu > main.cu_temp #>/dev/null 2>&1
+mv main.cu_temp main.cu
+echo -e "Threads defined: $2";
 
 
 echo -e "\nDone.\n";
